operations:
  ## Docker
  - name: "gitlab-runner-cleanup"
    filters:
      - column: I
        value: "gitlab-runner-docker-cleanup"
    actions:
      - column: K
        value: "Scheduled startup job"
  ## Windows
  - name: "aws-inspector-ssm-plugin-update"
    filters:
      - column: F
        value: "^Amazon Inspector SSM Plugin"
    actions:
      - column: P
        value: "Automatic action (AWS)"
  - name: "aws-ssm-agent-install"
    filters:
      - column: F
        value: "^Amazon SSM Agent"
    actions:
      - column: P
        value: "Automatic action (AWS)"
  ## RHEL
  - name: "2025-09-01-refresh-appian"
    filters:
      - column: B
        value: "^9/1/25 (18|19)"
    actions:
      - column: K
        value: "GPLS-8000"
      - column: L
        value: "GPLS-8001"
  - name: "2025-10-08-refresh-appian"
    filters:
      - column: B
        value: "^10/8/25 (18|19)"
    actions:
      - column: K
        value: "GPLS-8265"
      - column: L
        value: "GPLS-8286"
  - name: "2025-10-23-app-deployment-r3.11"
    filters:
      - column: B
        value: "^10/23/25 (18|19)"
    actions:
      - column: K
        value: "R3.11 Release"
      - column: L
        value: "GPLS-8178"
